/** The language, case by case against the `jq` binary — with the departures `divergent` documents. */
import { differential } from './harness.js';
import { lib } from '#/runtime/js/index.js';
import { runtime } from '#/runtime/js/runtime.js';

const { agree, divergent } = differential({ runtime, lib });

agree('paths and literals', [
	[ '.', { a: 1 } ],
	[ '.a', { a: 1 } ],
	[ '.a.b', { a: { b: 2 } } ],
	[ '.a.b.c', { a: null } ],
	[ '.a.b.c', {} ],
	[ '.a.b', { a: 1 } ],
	[ '.a[0].b', { a: [ { b: 9 } ] } ],
	[ '.["a"]', { a: 1 } ],
	[ '."a"', { a: 1 } ],
	[ '.a."b"', { a: { b: 2 } } ],
	[ '.a.[0]', { a: [ 1 ] } ],
	[ '.a[]', { a: [ 1, 2 ] } ],
	[ '.[1.7], .[-1], .[-1.5], .[3], .[1e10]', [ 1, 2, 3, 2 ] ],
	[ '.[null:2], .[1.5:2.5], .[-10:10], .[1:]', [ 1, 2, 3, 2 ] ],
	[ '.[1:], .[:-1], .[5:]', 'abcd' ],
	[ '.a, .[0], .[1:2], .["a"]', null ],
	[ '.["a","b"]', { a: 1, b: 2 } ],
	[ '.[(0,1)]', [ 5, 6 ] ],
	[ '(.,.)[0]', [ 1 ] ],
	[ '.if, .end', { if: 1, end: 2 } ],
	[ '.xx .yy', { xx: { yy: 7 } } ],
	[ '1, 1.5, "a", true, null, [], {}' ],
	[ '.5' ],
	[ '"\\u00e9\\n\\t\\"\\\\\\/"' ],
	[ '$__loc__' ],
	[ '.[]', 1 ],
	[ '.[0]', {} ],
	[ '.["a"]', [ 1 ] ],
	[ '.[0]', 'abc' ],
	[ '.[1:2]', 1 ],
	[ '..a', {} ],
	[ '1 == 1 == true' ],
]);

agree('operators', [
	[ '(1,2) + (10,20)' ],
	[ '1 + 2 * 3 - 4 / 2 % 3' ],
	[ '-1 + 2, -(1,2) * 3, 1 - -1' ],
	[ '[-.[]]', [ 1, 2 ] ],
	[ '-"a"' ],
	[ 'null + null, [1,2,3] - [2,4], "a,b,c" / ",", "" / ",", "abc" / "", 4 / 2' ],
	[ '{"a":1} + {"b":2}, {"a":{"b":1}} * {"a":{"c":2}}, "ab" * 2, 7 % 3, 7 / 2' ],
	[ '"ab" * 0, "ab" * 0.5, "ab" * -1, "ab" * 2.7, 7 % -3, -7 % 3, 5.7 % 2.2' ],
	[ '5 % 0' ],
	[ '1 / 0' ],
	[ '[] - 1' ],
	[ '{} + []' ],
	[ '{a:1,b:2} == {b:2,a:1}, 1 == 1.0, [1] == [1], ("a" < "b"), (false < true), (1 < 2), (2 <= 2)' ],
	[ 'sort', [ 'b', 'a', 'é', '😀', 'B', '' ] ],
	[ '[.[] | not]', [ true, false, null, 0, '' ] ],
	[ '[(true, false) and (true, false)]' ],
	[ '[(true, false) or (true, false)]' ],
	[ 'true and (1,null)' ],
	[ '[false and error("x")], [true or error("x")]' ],
	[ '[(1, null, 2) // 3], [(null, false) // 3], [empty // 3], [error("x") // 3]' ],
	[ '[(1, error("x")) // 3]' ],
	[ '[false // false], [null // null]' ],
	[ '[(1,2) // (3,4)], [(null) // (3,4)]' ],
	[ 'null // 3 | . + 1' ],
	[ '1 // 2 + 3' ],
	[ '1 + 2 // 3' ],
	[ '.a? // "d"', 1 ],
	[ '(.a | error) // "d"', { a: 'm' } ],
	[ '"a\\(1,2)b\\(3,4)"' ],
	[ '"\\(.a) and \\(.b)"', { a: 1, b: [ 2 ] } ],
	[ '"x\\("y\\("z")")"' ],
]);

agree('construction', [
	[ '[.[] | . + 1]', [ 1, 2, 3 ] ],
	[ '[]' ],
	[ '{a: .b, c: 1}', { b: 5 } ],
	[ '{a: (1,2), b: (3,4)}' ],
	[ '{(("x","y")): (1,2)}' ],
	[ '{"a": (1,2)}' ],
	[ '{(.[]): 1}', [ 'a', 'b' ] ],
	[ '{"a", "b"}', { a: 1, b: 2 } ],
	[ '{$__loc__}' ],
	[ '{a: .b?}', { b: 1 } ],
	[ '{a: -1}, {a: 1 | . + 1}, {a: try 1}, {a: if . then 1 else 2 end}', true ],
	[ '{a: reduce .[] as $x (0; .+$x)}', [ 1, 2 ] ],
	[ '[1, # one\n 2] # two' ],
	[ '1 # a comment ending in a backslash continues \\\n + 2' ],
	[ '1 # two backslashes do not \\\\\n + 2' ],
	[ '1 # three do \\\\\\\n + 2 \\\n + 3' ],
	[ '{a: .b.c[0]?, b: .x[]}', { b: { c: [ 9 ] }, x: [ 1, 2 ] } ],
	[ '{"a"}', { a: 1 } ],
	[ '{a: 1}.a' ],
	[ '{a: 1, a: 2}' ],
	[ '{if: 1, then: 2}' ],
	[ '{(1): 2}' ],
	[ '{"\\(.k)": 1}', { k: 'z' } ],
	[ '{"\\(.k)"}', { k: 'z', z: 5 } ],
	[ '.a as $x | {$x, y: 2, "z": 3, ("w"): 4, "i\\($x)": 6, a}', { a: 1 } ],
	[ '"a" as $k | {$k: 1}' ],
	[ '[1,2][0]', null ],
	[ '"abc"[1:]' ],
	[ '{"__proto__": 1} | .__proto__, keys, ({"__proto__": 2} + .), tojson' ],
	[ '{__proto__: 1}.__proto__' ],
	[ '.constructor, .toString', {} ],
]);

agree('control flow', [
	[ 'if . then "t" elif . == null then "n" else "f" end', false ],
	[ '[if (true,false) then 1 else 2 end]' ],
	[ 'if true then 1 end, [.[] | if . then "y" end]', [ true, false ] ],
	[ 'if (true,false) then (1,2) else (3,4) end' ],
	[ 'if . then 1 else 2 end | . + 1', true ],
	[ 'if . then 1 else 2 end + 1', true ],
	[ '[try 1 + error("x")]' ],
	[ '[try error("x") catch 2, 3]' ],
	[ '[1?, (1,error("x"))?]' ],
	[ 'try error("x") catch .' ],
	[ '[.[] | try error catch .]', [ 1, 'a', { a: 1 }, null ] ],
	[ 'error(null)' ],
	[ 'error' ],
	[ '[try (1,2,error("x"),3) catch "c"], [try (1, error("x"), 2)], [(1, error("x"))?]' ],
	[ 'try (1,2) catch "c" | error("y")' ],
	[ '[.[] | try (if . == 2 then error("e") else . end) catch "c"]', [ 1, 2, 3 ] ],
	[ 'try error("\\(1)") catch (. | ascii_upcase)' ],
	[ '(try error("x") catch .) | length' ],
	[ 'try error("x") catch . + "y"' ],
	[ 'try error("x") catch . | ascii_upcase' ],
	[ 'try 1 catch 2 + 1' ],
	[ '.a[]?', { a: 1 } ],
	[ '[.[] | tonumber?]', [ '1', 'x', '2' ] ],
	[ '[.[] | .a?]', [ [ 1 ], { a: 2 }, 's', null, 3 ] ],
	[ '[.[]?]', 5 ],
	[ '.a?.b, .a?[0], ..?', { a: null } ],
	[ '[.[] | (1 / .)?]', [ 0, 1 ] ],
	[ '[.[]|(.a,.b)?]', [ { a: 1, b: 2 }, 1 ] ],
	[ 'try error("x") catch error("y")' ],
	[ '[.[] | select(. > 1)]', [ 1, 2, 3 ] ],
	[ '[.[] | select(.a)?]', [ 1, { a: true } ] ],
	[ 'label $out | 1, 2, break $out, 3' ],
	[ '[label $f | range(10) | ., (select(. == 3) | break $f)]' ],
	[ 'break $x' ],
	[ '[try (label $out | break $out) catch "caught"]' ],
	[ 'label $x | 1, break $x | . + 1' ],
	[ 'label $a | label $b | 1, break $a, 2' ],
	[ '[label $a | (label $b | 1, break $b, 2), 3]' ],
	[ 'def f(g): label $out | g; [f(1, break $out, 2)]' ],
	[ 'label $out | def f: 1, break $out, 2; [f]' ],
]);

agree('generators', [
	[ '[range(5)], [range(0;10;3)], [range(5;0;-2)], [range(2.5)], [range(-1)], [range(1;3;0.5)]' ],
	[ '[range(0;3;-1)], [range(3;0;-1)], [limit(3; range(0;1;0))]' ],
	[ 'range("a")' ],
	[ 'range(1;null)' ],
	[ '[limit(3; range(10))], [limit(1; 1, error("x"))], first(1, error("x")), [first(range(10;0;-1))]' ],
	[ '[limit(0; error("x"))], [limit(1.5; 1,2,3)], [limit(0.5; 1,2,3)]' ],
	[ '[limit(-1; 1,2)]' ],
	[ 'isempty(empty), isempty(1, error("x"))' ],
	[ '[first, last], ([] | first, last)', [ 7, 8, 9 ] ],
	[ 'nth(-1; 1)' ],
	[ '[skip(-1; 1,2,3)]' ],
	[ 'first(empty), [first(1,2)]' ],
	[ 'until(. > 10; . * 2), [while(. < 10; . * 2)]', 1 ],
	[ '[recurse(if . < 3 then . + 1 else empty end)]', 1 ],
	[ '[..]', { a: [ { b: 1 } ] } ],
	[ '[.. | select(type == "number")]', { a: [ { b: 1 } ] } ],
	[ '[recurse(.a?)]', { a: { a: 1 } } ],
	[ '[recurse(.[]?, .[]?)]', [ [ 1 ] ] ],
	[ '.. == 1', [ 1 ] ],
	[ 'reduce range(3) as $x (0; empty)' ],
	[ '[reduce range(3) as $x ((0,10); .+$x)]' ],
	[ 'reduce range(3) as $x (0; ., 100)' ],
	[ 'reduce empty as $x (1; 2)' ],
	[ '[reduce (1,2) as $x (empty; 2)]' ],
	[ '[foreach range(3) as $x (0; (.+$x, .-$x))]' ],
	[ '[foreach range(3) as $x (0; empty; .)]' ],
	[ '[foreach (1,2) as $x ((0,10); . + $x)]' ],
	[ '[foreach (1,2) as $x (0; . + $x; (., .))]' ],
	[ '[limit(2; foreach range(10) as $x (0; . + $x))]' ],
	[ 'reduce .[] as [$a,$b] (0; . + $a * $b)', [ [ 1, 2 ], [ 3, 4 ] ] ],
	[ '[foreach .[] as $x (0; . + $x; [$x, .])]', [ 1, 2, 3 ] ],
	[ 'reduce .[] as $x (0; . + $x) | . + 1', [ 1, 2 ] ],
	[ 'reduce .[] as $x (0; . + $x) + 1', [ 1, 2 ] ],
	[ 'reduce .[] as $x (0; . + $x) as $s | $s', [ 1, 2 ] ],
	[ 'reduce ([1],2) as [$a] ?// $a (0; . + $a)' ],
	[ 'reduce ([1],"x") as [$a] ?// $a (0; . + $a)' ],
	[ '[foreach ([1],2) as [$a] ?// $a (0; . + $a; [$a, .])]' ],
	[ '[.[] | (., . * 2)]', [ 1, 2 ] ],
	[ '[(1,2) | (., . * 10) | (., . + 100)]' ],
	[ '[(1,2), (3,4) | (., . * 10) | (., . + 100) | (., . + 1000) | tostring | ascii_downcase | ltrimstr("x") | ascii_upcase]' ],
]);

agree('variables and functions', [
	[ '1 as $x | 2 as $x | $x' ],
	[ '1 as $x | 2 as $y | [$x, $y, .]', 0 ],
	[ '[.[] as [$a, $b] | {a: $a, b: $b}]', [ [ 1, 2 ], [ 3 ] ] ],
	[ '. as {a: $x, $b} | [$x, $b]', { a: 1, b: 2 } ],
	[ '. as {$a: [$b]} | [$a,$b]', { a: [ 5 ] } ],
	[ '. as {("a","b"): $x} | $x', { a: 1, b: 2 } ],
	[ '. as {"a": $x} | $x', { a: 1 } ],
	[ '. as [$a] | $a', { a: 1 } ],
	[ '.[] as [$a] ?// $a | $a', [ [ 1 ], 2 ] ],
	[ '[.[] as [$a] ?// $a | if ($a|type)=="number" then $a else error("e") end]', [ [ 1 ], 2 ] ],
	[ '[.[] as [$a] ?// [$b] | [$a, $b]]', [ [ 1 ] ] ],
	[ '[.[] as [$a] ?// $a | error("e")]', [ [ 1 ] ] ],
	[ '. as [$a] ?// $a | [$a]', 1 ],
	[ '[. as $x | $x, 1]', 5 ],
	[ '[.[] as $x | $x | . + 1, 2]', [ 10 ] ],
	[ '. as $x | . as $y | $x + $y', 1 ],
	[ '$x' ],
	[ '"abc" as $x | $x[1:]' ],
	[ 'def f: def g: 3; g; f' ],
	[ 'def f($x; $y): [$x,$y]; [f(1,2; 3,4)]' ],
	[ 'def f(x): [x]; f(1,2)' ],
	[ 'def f($x): $x; [f(1,2)]' ],
	[ 'def f: 1; def f: 2; f' ],
	[ 'def f: 1; def f(x): x; [f, f(2)]' ],
	[ 'def f(f): f; f(3)' ],
	[ 'def f: def g: f; if . > 0 then . - 1 | g else . end; 3 | f' ],
	[ 'def r: if . < 3 then . + 1 | r else . end; 0 | r' ],
	[ 'def fac: if . <= 1 then 1 else . * (. - 1 | fac) end; fac', 5 ],
	[ 'def f(g): def h: g; h; f(. + 1)', 1 ],
	[ 'def f(g): 5 | g; . as $x | f($x + .)', 10 ],
	[ 'def f(g): [g, g]; f(1,2)' ],
	[ 'def f(g): g | g; f(. + 1)', 1 ],
	[ 'def f: reduce .[] as $x (0; . + $x); f', [ 1, 2 ] ],
	[ 'def f: 1;', 9 ],
	[ 'def f: 1; f | . + 1' ],
	[ 'def f: 1; f + 1' ],
	[ '(def f: 1; f) + 1' ],
	[ '1 as $x | def f: $x; 2 as $x | f' ],
	[ 'def f(x): x; def g: f(.); g', 3 ],
	[ 'def f($x): $x | def g: $x; g; f(1)' ],
	[ 'def f(g): def f: 3; g + f; f(1)' ],
	[ 'def f: 1; def g: f; def f: 2; g' ],
	[ 'def f($a; $a): $a; f(1;2)' ],
	[ 'def f(a; $a): a; f(1;2)' ],
	[ 'def f($x): x; f(1)' ],
	[ 'def f(x): $x; f(1)' ],
	[ 'def f(a): a; f(1; 2)' ],
	[ 'f' ],
	[ 'def f(g): if . > 3 then . else (. + 1 | f(g)) end; f(.)', 0 ],
	[ 'def f(g): g, (if . < 3 then . + 1 | f(g) else empty end); [f(. * 10)]', 0 ],
	[ 'def f($n; g): if $n == 0 then g else (f($n - 1; g) | . + 1) end; f(3; .)', 0 ],
	[ 'def f(g): [path(g)], (if .a then .a | f(g) else empty end); f(.b, .c)', { a: { a: 1, b: 2 }, b: 1 } ],
	[ '[.[] | def f: . * 2; f]', [ 1, 2 ] ],
	[ 'def r: if . > 0 then (. - 1 | r), . else . end; [3 | r]' ],
	[ 'def cnt: if . >= 1000 then . else . + 1 | cnt end; 0 | cnt' ],
	[ 'until(. >= 100000; . + 1)', 0 ],
]);

agree('assignment and paths', [
	[ 'path(.), [paths], path(..)', { a: [ 1, { b: 2 } ] } ],
	[ 'path(.a[].b)', { a: [ { b: 1 }, { b: 2 } ] } ],
	[ 'path(.a // .b)', { b: 1 } ],
	[ 'path(first(.a,.b)), path(.a | select(. == 1)), path(.a as $x | .b)', { a: 1 } ],
	[ 'path(1)' ],
	[ 'path(.a | 1)', { a: 1 } ],
	[ 'path(getpath(["x","y"]))', { x: null } ],
	[ 'path(.[1:3]), path(.a?), path(.[]?), path(empty)', 1 ],
	[ 'path(if .a then .b else .c end), path(.a?), path(.a.b?)', null ],
	[ 'path(.. | select(type=="number"))', [ 1, [ 2 ] ] ],
	[ 'path(limit(2; .[]))', [ 1, 2, 3 ] ],
	[ 'path(.a[1:2])', { a: [ 1, 2, 3 ] } ],
	[ 'path(label $x | .a, break $x, .b)', {} ],
	[ '[paths]', [ [ 1 ] ] ],
	[ '.a |= . + 1', { a: 1 } ],
	[ '.[] |= empty', [ 1, 2, 3, 4, 5 ] ],
	[ '.[] |= empty', { a: 1, b: 2 } ],
	[ '(.[] | select(. == 2)) |= empty', [ 1, 2, 3 ] ],
	[ '.a |= empty', { a: 1, b: 2 } ],
	[ '.a |= (1,2)', { a: 0 } ],
	[ '.a += (1,2)', { a: 0 } ],
	[ '.a = (.b, .c)', { a: 0, b: 1, c: 2 } ],
	[ '.[] += 1', { a: 1 } ],
	[ '.a.b.c = 1' ],
	[ '.[2] = 1', [] ],
	[ '.[-1] = 9', [ 1, 2 ] ],
	[ '.[-5] = 1', [ 1 ] ],
	[ '.[1:2] = ["x","y"]', [ 1, 2, 3 ] ],
	[ '.[1:2] |= map(.+1)', [ 1, 2, 3 ] ],
	[ '.[1:] = "x"', [ 1, 2 ] ],
	[ '.a //= 3', { a: null } ],
	[ '(.a,.b) |= .+1', { a: 1, b: 2 } ],
	[ '(.a, .a) |= . + 1', { a: 1 } ],
	[ '.a += .a', { a: 1 } ],
	[ '. |= 2' ],
	[ 'getpath(["a","b"]) = 1' ],
	[ '.a[] |= .+1', { a: [ 1, 2 ] } ],
	[ '.[] = 1', [ 0, 0 ] ],
	[ '.. |= (if type == "number" then . + 1 else . end)', [ 1, [ 2 ] ] ],
	[ '[range(3)] | .[1:] |= map(. * 10)' ],
	[ '.[] |= . + 1', Array.from({ length: 2000 }, (_value, ii) => ii) ],
	[ 'del(.a, .b), del(.[])', { a: 1, b: 2, c: 3 } ],
	[ 'del(.[1], .[0])', [ 1, 2, 3 ] ],
	[ 'del(.[0,2]), del(.[] | select(. == 2))', [ 0, 1, 2, 3 ] ],
	[ 'del(.[2:4]), del(.[0], .[2:4])', [ 0, 1, 2, 3, 4, 5 ] ],
	[ 'del(.a), del(.[0])', null ],
	[ 'delpaths([[0],[1]])', [ 1, 2, 3 ] ],
	[ 'delpaths([[5]]), delpaths([]), delpaths([[]])', [ 1 ] ],
	[ 'delpaths([["a"]])', [ 1 ] ],
	[ 'delpaths(1)', 1 ],
	[ 'getpath(["a","b"]), getpath(["a","b","c"])', { a: { b: null } } ],
	[ 'getpath(["a","b"])', { a: 1 } ],
	[ 'getpath([]), getpath(1)', 1 ],
	[ 'setpath([]; 1), setpath(["a",1]; 1), setpath([1.5]; 1)', null ],
	[ 'setpath(["a","b"]; 1)', { a: [] } ],
	[ 'setpath([0]; 1)', {} ],
	[ 'to_entries, from_entries', { b: 1, a: 2 } ],
	[ 'to_entries', [ 1 ] ],
	[ 'from_entries', [ { name: 'a', value: 1 }, { k: 'b', v: 2 }, { Key: 'c', Value: 3 }, { key: 4 }, { key: true, value: 5 } ] ],
	[ 'from_entries', [ { key: null, value: 5 } ] ],
	[ 'from_entries', [ [ 1 ] ] ],
	[ 'with_entries(.value += 1)', { b: 1, a: 2 } ],
	[ 'with_entries(empty), with_entries(.key |= ascii_upcase)', { a: 1 } ],
	[ 'walk(if type == "number" then . + 1 else . end), walk(if type == "object" then del(.a) else . end)', { b: [ 1, { a: 2 } ], a: 1 } ],
	[ 'getpath(["a"]) |= 1', {} ],
	[ 'to_entries[0] | .key', { a: 1 } ],
	[ 'if . then 1 else 2 end.a', { a: 1 } ],
	[ 'path(.a | .b?)', { a: 1 } ],
	[ 'path(try .a catch .b)', null ],
	[ '[path(.a, .b | .c)]', {} ],
	[ 'path(reduce .[] as $x (.; .[$x]))', [ 0, 1 ] ],
	[ 'path(foreach ("a","b") as $k (.; .[$k]) | select(false))' ],
	[ '[path(foreach ("a","b") as $k (.; .[$k]; empty))]' ],
]);

agree('builtins', [
	[ '[.[] | length]', [ null, -5, 'héllo', { a: 1 }, [ 1, 2 ] ] ],
	[ 'true | length' ],
	[ 'keys, length', [ 3, 1 ] ],
	[ 'keys', 'a' ],
	[ 'has("a"), has("z")', { a: 1 } ],
	[ 'has(0), has(5)', [ 1 ] ],
	[ 'has("a")', [ 1 ] ],
	[ 'contains("x")', { a: [ 1, 2 ] } ],
	[ 'contains("a")', 1 ],
	[ '[.[] | type]', [ null, true, 1, 'a', [], {} ] ],
	[ '[.[] | tostring]', [ 1, '1', null, true, [ 1 ], { a: 'b' } ] ],
	[ '[.[] | try tonumber catch "E"]', [ '1', '1.50', ' 1', '1 ', '+1', '.5', '5.', '1e', '1e3', 'nan', '0x1', '', '1_0', '١' ] ],
	[ 'tonumber', true ],
	[ 'fromjson', '[1, {"a": 2}] ' ],
	[ 'fromjson', '[1,' ],
	[ 'fromjson', '1 2' ],
	[ 'tojson', { a: [ 1, 'x' ] } ],
	[ 'tojson, (" " | tojson), ("😀" | tojson), ("a\\"b\\\\c/d" | tojson)', 'x' ],
	[ '[1,{"a":"b"}] | tojson, tostring' ],
	[ 'add', [ 1, 2, 3 ] ],
	[ 'add', { a: 1, b: 2 } ],
	[ 'add', [ 'a', 'b' ] ],
	[ 'add, any, all, unique', [] ],
	[ 'any, all', [ null, true ] ],
	[ 'any, all', 'a' ],
	[ 'any, all', [] ],
	[ 'flatten', [ [ 1, [ 2 ] ], [ 3 ] ] ],
	[ 'flatten(-1)', [ 1 ] ],
	[ 'flatten', 1 ],
	[ 'sort_by(.a, .b), group_by(.a)', [ { a: 2, b: 1 }, { a: 1, b: 2 }, { a: 2, b: 0 }, { a: 1, b: 3 } ] ],
	[ 'unique', [ 'bb', 'a', 'a', 'cc' ] ],
	[ 'ascii_downcase, ascii_upcase, ltrimstr("h"), rtrimstr("o"), startswith("hé"), endswith("o")', 'héllo' ],
	[ 'startswith(1)', 'abc' ],
	[ 'ltrimstr("ab"), ltrimstr(""), ltrimstr("x")', 'abab' ],
	[ 'ascii_downcase', 1 ],
	[ 'split("b"), split("")', 'abcb' ],
	[ 'join("-"), (["a",null,1,true] | join(",")), ([] | join(","))', [ 1, 2 ] ],
	[ 'join(",")', [ {} ] ],
	[ 'join(",")', 'a' ],
	[ 'test("A";"i"), test("a"; "g")', 'a1ba2ca3' ],
	[ 'test("a"; "q")', 'a' ],
	[ 'test("(")', 'a' ],
	[ 'split("[0-9]"; null), split("b";"g"), sub("a";"X"), gsub("a";"X"), sub("(?<l>[a-z])"; "[\\(.l)]"; "g"), [match("a";"g").offset], (match("(a)(x)?") | [.captures[].string]), [match("";"g") | .offset]', 'a1ba2ca3' ],
	[ '[match("(?<n>\\\\d)(x)?"; "g")]', 'a1b' ],
	[ '[match("\\\\p{L}+"; "g").string]', 'héllo wörld' ],
	[ '[match("(a)|(b)";"g") | .captures | map(.string)]', 'ab' ],
	[ 'sub("a";"b";"gi"), gsub("A";"b"), sub("";"-"), gsub("";"-"), gsub("^";"-"), gsub("$";"-"), [match("a*";"g") | [.offset,.length]]', 'aAa' ],
	[ 'gsub("\\\\s+";" "), gsub("\\\\d"; "\\(.)")', 'a  b 1' ],
	[ 'test("a.b"), test("A";"i")', 'a\nb' ],
	[ 'sub("(?<a>.)"; .a + "|")', 'xy' ],
	[ '[sub("a"; ("1","2"))], [gsub("a"; ("1","2"))], [sub("a"; "\\(1,2)")]', 'aa' ],
	[ '[.[] | gsub("(?<x>a)|(?<y>b)"; "<\\(.x)\\(.y)>")]', [ 'ab' ] ],
	[ 'gsub("\\\\b"; "|"), gsub("(?=a)"; "|")', 'ab aa' ],
	[ 'splits("a")', 1 ],
	[ 'sub("a";"b")', [ 'a' ] ],
	[ 'sub("a"; 1)', 'a' ],
	[ 'split(""; null), [match(""; "g")] | length', 'ab' ],
	[ '@json, @text', [ 1, 'a"b\tc\\d\n<&>\'', null, true, 1.5 ] ],
	[ '@csv', 1 ],
	[ '@csv', [ [ 1 ] ] ],
	[ '@base64, (@base64 | @base64d)', 'a b&c=d/é~!*()' ],
	[ '@text "a\\(1)", @base64 "x\\(.)y", @json "v=\\(.)"', { a: 1, b: [ 2 ] } ],
	[ '@foo', 1 ],
	[ 'tostring', ' ' ],
	[ '"a\\u0001" | tojson' ],
	[ 'map(. * 2), map(select(. > 1))', [ 1, 2, 3 ] ],
	[ 'map(.+1)', { a: 1 } ],
	[ 'map(.+1)', 1 ],
	[ 'to_entries', 1 ],
	[ '$ENV | type, ($ENV.PATH | type), ($ENV.__nonexistent__)' ],
	[ 'floor, sqrt, pow(.;2)', 5.5 ],
	[ 'getpath(["a"]) as $x | $x', { a: 1 } ],
	[ 'splits' ],
	[ 'error(1;2)' ],
	[ 'tojson(1)' ],
	[ 'ltrimstr("a";"b")', 'a' ],
	[ '[limit(5; inputs)]', 0, [ 1, 2, 3 ] ],
	[ '[., input]', 0, [ 1, 2, 3 ] ],
	[ 'input', 0 ],
	[ 'debug', [ 1 ] ],
	[ 'strftime(1)', 1425599621 ],
	[ 'strftime("%Y")', 'a' ],
	[ 'strptime("%Y-%m-%d"), strptime("%d %B %Y")', '2015-03-05' ],
	[ 'strptime("%Y")', 'abc' ],
]);

divergent('jq 1.8 quirks not followed', [
	// jq 1.8.2's `repeat` yields `f` of the same input forever; the documented definition is kept
	[ '[limit(5; repeat(. * 2))]', 1, [ [ 1, 2, 4, 8, 16 ] ] ],
	[ '[limit(3; repeat(. * 2, . * 3))]', 1, [ [ 1, 2, 4 ] ] ],
	// jq tracks paths through `reduce` and `foreach` only by accident: the path resets whenever the
	// fold is backtracked into (`[path(…)]` of the same fold gives `[[]]`), and any non-null value
	// along the way is an "Invalid path expression". Here the state is a path and its value
	// throughout, as `getpath` would have it.
	[ 'path(reduce ("a","b") as $k (.; .[$k]))', { a: { b: 1 } }, [ [ 'a', 'b' ] ] ],
	[ '[path(reduce (0,1) as $x (.; .[$x]))]', null, [ [ [ 0, 1 ] ] ] ],
	[ '[path(foreach ("a","b") as $k (.; .[$k]))]', null, [ [ [ 'a' ], [ 'a', 'b' ] ] ] ],
	[ '[path(foreach ("a","b") as $k (.; .[$k]; .x))]', null, [ [ [ 'a', 'x' ], [ 'a', 'b', 'x' ] ] ] ],
	[ '[path(reduce (0,1) as $x (.; .[$x], .[$x + 10]))]', null, [ [ [ 10, 11 ] ] ] ],
	[ 'path(reduce (["a"],["b"]) as [$k] (.; .[$k]))', null, [ [ 'a', 'b' ] ] ],
	[ 'reduce ("a","b") as $k (.; .[$k]) = 1', {}, [ { a: { b: 1 } } ] ],
	[ 'reduce range(1) as $x (.a; .b) |= 5', {}, [ { a: { b: 5 } } ] ],
	[ 'path(reduce range(1) as $x (.a; empty))', null, 'error' ],
	// When a later `?//` pattern is tried inside a fold, jq 1.8.2 loses the state accumulated so far
	// (it yields 1, 3, 3); the state before the failed update is kept
	[ '[foreach ([1],2,{"a":3}) as [$a] ?// $a ?// {a: $a} (0; . + $a)]', null, [ [ 1, 3, 6 ] ] ],
]);

agree('the prelude: builtins defined in the language', [
	[ '[.[] | values]', [ 1, null, 'a', false, null ] ],
	[ '[.[] | nulls], [.[] | booleans], [.[] | numbers], [.[] | strings]', [ null, true, 1, 'a', [ 1 ], { a: 1 } ] ],
	[ '[.[] | arrays], [.[] | objects], [.[] | iterables], [.[] | scalars]', [ null, true, 1, 'a', [ 1 ], { a: 1 } ] ],
	[ '[.[] | abs]', [ -1, 2, -3.5, 0 ] ],
	[ '[.[] | toboolean]', [ 'true', 'false', true, false ] ],
	[ 'try toboolean catch "E"', 'nope' ],
	[ 'add(.[] | . * 2)', [ 1, 2, 3 ] ],
	[ 'map_values(. + 1)', { a: 1, b: 2 } ],
	[ 'map_values(. + 1)', [ 1, 2 ] ],
	[ '[paths(type == "number")]', { a: 1, b: [ 2, 'x' ] } ],
	[ '[paths(scalars)]', { a: 1, b: [ 2, { c: null } ] } ],
	[ '[.[] | in({"a": 1, "b": 2})]', [ 'a', 'x' ] ],
	[ '[.[] | in([10, 20])]', [ 0, 5 ] ],
	[ '[limit(5; recurse(. * 2; . < 100))]', 1 ],
	[ '[recurse]', { a: [ 1, { b: 2 } ] } ],
	[ 'last(range(10))' ],
	[ 'last(empty)' ],
	[ 'nth(2)', [ 'a', 'b', 'c', 'd' ] ],
	[ 'nth(2; range(10))' ],
	[ 'try nth(-1; range(3)) catch "E"' ],
	[ '[any(range(3); . == 2), any(range(3); . == 5), any(empty; .), all(range(3); . < 5), all(range(3); . < 2), all(empty; .)]' ],
	[ '[any(. == 2), all(. > 0)]', [ 1, 2, 3 ] ],
	[ '[.[] | IN("a", "b")]', [ 'a', 'x' ] ],
	[ 'INDEX(.id)', [ { id: 'a', v: 1 }, { id: 'b', v: 2 } ] ],
	[ 'INDEX(.[]; .id)', [ { id: 'a' }, { id: 'b' } ] ],
	[ '[combinations]', [ [ 1, 2 ], [ 3, 4 ] ] ],
	[ '[limit(4; combinations(2))]', [ 0, 1 ] ],
	[ 'transpose', [ [ 1, 2 ], [ 3 ] ] ],
	[ 'transpose', [] ],
	[ 'pick(.a, .b.c)', { a: 1, b: { c: 2, d: 3 }, e: 4 } ],
	[ '[splits(", *")]', 'a, b,c' ],
	[ '[splits("a"; "i")]', 'xAyaz' ],
	[ 'capture("(?<x>[0-9]+)-(?<y>[a-z]+)")', '123-abc' ],
	[ '[scan("[0-9]+")]', 'a1b22c333' ],
	[ '[scan("([0-9])([a-z])")]', '1a 2b' ],
	// The program's own definitions shadow the prelude's
	[ 'def values: 42; values', null ],
	[ 'def abs: "mine"; [.[] | abs]', [ -1 ] ],
]);

agree('the source of `as` runs up to a comma', [
	[ '. - 1 as $n | $n + 10', 5 ],
	[ '1, 2 as $x | $x, 3' ],
	[ '1 as $x | $x, 3' ],
	[ 'true and false as $x | 5' ],
	[ 'false or true as $x | 5' ],
	[ 'true // 3 as $x | 10' ],
	[ '.[]? // 3 as $x | $x', {} ],
	[ '.a = 2 as $x | 99', {} ],
	[ '.a |= 7 as $x | 99', { a: 1 } ],
	[ '1 < 2 as $x | 5' ],
	[ '- .a as $x | 5', { a: 3 } ],
	[ '1 + 2 as $x | $x * 10' ],
	[ '2 as $x | . - $x as $y | $y', 5 ],
	[ '2 as $x | $x as $y | $y' ],
	[ 'if true then 1 else 2 end as $x | $x' ],
	[ 'def f: 2; f + 1 as $x | $x' ],
	[ '.[] as $x | $x', [ 7, 8 ] ],
	[ '. as [$a, $b] | $a + $b', [ 1, 2 ] ],
	[ 'reduce .[] + 1 as $x (0; . + $x)', [ 1, 2, 3 ] ],
	[ 'foreach .[] + 1 as $x (0; . + $x)', [ 1, 2 ] ],
	[ '{a: 2 as $x | $x}' ],
	[ '[1 as $x | $x]' ],
]);

agree('the math tail', [
	[ '[.[] | fabs, ceil, floor, trunc, round]', [ -1.7, 2.5, 3.5, -1.5, -2.5, 2.3 ] ],
	[ '-0.5 | round' ],
	[ '[.[] | sqrt]', [ 4, 2, 0.25 ] ],
	[ '[.[] | cbrt]', [ -8, 0.5 ] ],
	[ '[.[] | exp, expm1]', [ 0, 1, 2, 3, 0.1 ] ],
	[ '[.[] | log, log2, log10, log1p]', [ 1, 8, 100, 2, 0.5 ] ],
	[ '[.[] | sin, cos, tan, sinh, cosh, tanh]', [ 0, 1, -0.5 ] ],
	[ '[.[] | asin, atan, asinh]', [ 0, 0.5, 1 ] ],
	[ '0 | atanh' ],
	[ '[.[] | acos]', [ 1, 0.5 ] ],
	[ '1 | acosh' ],
	[ '[hypot(3; 4), atan2(1; 1), pow(2; 10)]' ],
	[ 'infinite, (nan | isnan), (nan | tojson)' ],
	[ '[.[] | isinfinite, isfinite, isnormal]', [ 1, 0 ] ],
	[ '[infinite, -infinite | isinfinite, isfinite, isnormal]' ],
	[ '1e-320 | isnormal' ],
	[ 'sqrt', 'x' ],
	[ 'pow(2; "x")' ],
]);

agree('the strings tail', [
	[ 'explode', 'abc' ],
	[ 'explode | implode', 'héllo 😀' ],
	[ '[104, 105] | implode' ],
	[ '["x"] | implode' ],
	[ 'utf8bytelength', 'héllo' ],
	[ 'utf8bytelength', 'a😀b' ],
	[ '[ltrim, rtrim, trim]', ' \tx y\n ' ],
	[ '[ltrim, rtrim, trim]', 'x' ],
	[ 'trimstr("x")', 'xxaxx' ],
	[ 'trimstr("ab")', 'abZab' ],
	[ '[index("c"), rindex("bc"), indices("bc")]', 'abcbc' ],
	[ 'indices("aa")', 'aaa' ],
	[ 'indices("")', 'abc' ],
	[ 'indices("x")', '' ],
	[ 'indices(1)', null ],
	[ 'indices([1, 2])', [ 1, 2, 1, 2, 1 ] ],
	[ 'indices(1)', [ 0, 1, 2, 1 ] ],
	[ '[index([1, 2]), rindex([1, 2])]', [ 1, 2, 1, 2 ] ],
	[ 'indices("a")', 1 ],
	[ 'contains("b"), contains("x")', 'abc' ],
	[ 'contains(["b"])', [ 'ab', 'c' ] ],
	[ 'contains({a: {}}), contains({a: {b: 2}}), contains({c: 1})', { a: { b: 1 }, c: 1 } ],
	[ 'contains(1)', 1 ],
	[ 'contains(["a"])', 'ab' ],
	[ '"b" | inside("abc"), inside("xyz")' ],
	[ '[1] | inside([[1], 2])' ],
]);

agree('the order seam tail', [
	[ 'min, max', [ 3, 1, 2 ] ],
	[ 'min, max', [] ],
	[ 'min_by(.a), max_by(.a)', [ { a: 1, i: 0 }, { a: 2 }, { a: 1, i: 1 } ] ],
	[ 'min_by(.[])', [ [ 1 ], [ 0, 9 ] ] ],
	[ 'unique_by(. % 2)', [ 1, 2, 2, 3 ] ],
	[ 'unique_by(length)', [ 'a', 'bb', 'c', 'ddd' ] ],
	[ '[bsearch(3), bsearch(4), bsearch(0)]', [ 1, 3, 5 ] ],
	[ 'bsearch(1)', [] ],
	[ 'bsearch("b")', [ 'a', 'c' ] ],
]);

agree('streams', [
	[ '[tostream]', [ 1, [ 2, 3 ] ] ],
	[ '[tostream]', [ [], {} ] ],
	[ '[tostream]', { a: { b: 1 } } ],
	[ '[tostream]', 5 ],
	[ '[tostream]', [] ],
	[ '[fromstream(tostream)]', { a: [ 1, { b: null } ], c: false } ],
	[ '[1 | truncate_stream([1, [ 2, 3 ]] | tostream)]' ],
	[ '[fromstream([[0], 1], [[1, 0], 2], [[1, 1], 3], [[1, 1]], [[1]])]' ],
]);

agree('the odds and ends', [
	[ 'env | type' ],
	[ '$ENV | type' ],
	[ '(env.PATH == $ENV.PATH)' ],
	[ 'format("json"), format("text")', [ 'a', 1 ] ],
	[ 'format("csv")', [ 1, 'a' ] ],
	[ '@csv, @tsv, format("csv"), format("tsv")', [ 1, 'a"b', null, true ] ],
	[ '@tsv', [ 'a\tb\nc\\d', 1 ] ],
	[ '@html', '<b>&\'"</b>' ],
	[ '@uri', 'a b&c=!*\'()' ],
	[ '@sh', [ 'a b', 'it\'s', 3 ] ],
	[ '@sh', 'plain' ],
	[ '@csv', [ [ 1 ] ] ],
	[ '@sh', { a: 1 } ],
	[ '@base64 | @base64d', 'hi there' ],
	[ 'format("nope")', null ],

	[ 'debug("m")', 1 ],
	[ 'now | floor | . > 1400000000' ],
	[ 'now | type' ],
	[ '"2015-03-05T23:51:47Z" | fromdate' ],
	[ '"x" | fromdate' ],
	[ '[limit(3; skip(2; range(10)))]' ],
	[ '[skip(0; 1, 2)]' ],
	[ 'skip(-1; 1)' ],
	[ '[.[] | flatten, flatten(1), flatten(0)]', [ [ 1, [ 2, [ 3 ] ] ] ] ],
	[ 'flatten(-1)', [] ],
	[ 'keys_unsorted', { b: 1, a: 2 } ],
	[ 'keys_unsorted', [ 5, 6 ] ],
	[ 'keys_unsorted', 1 ],
	[ 'JOIN({a: 1}; .k)', [ { k: 'a' }, { k: 'b' } ] ],
	[ 'null | [JOIN({a: 5}; ({k: "a"}, {k: "b"}); .k)]' ],
	[ 'null | [JOIN({a: 5}; ({k: "a"}, {k: "b"}); .k; [.[0].k, .[1]])]' ],
]);
