name: jssq

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build & Lint
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - uses: pnpm/action-setup@v6
        with:
          cache: true

      # Build & lint
      - run: |
          pnpm install --frozen-lockfile
          pnpm run -s build
          pnpm run -s lint
